### ISSUE TITLE
Demi-Pheonix not combining with owner

### ISSUE THREAD

**Issue by isar-andrei** [HAERUHAERU/mopimopi#2]
I have checked the combine pets with owners option in the settings, but it doesn't do it for demi-pheonix https://i.imgur.com/Mm9t2VD.png . And a question that I have, is it possible to filter out the damage done by the limit break?

**Comment by dmill-bz** [comment]
It doesn't do it for seraph either (sch ultimate skill)

**Comment by dmill-bz** [comment]
I have a temp workaround for this. In you overlay manager add a new url that is the same as the old one but replace `haeruhaeru` with `pommeverte`. So something along the lines of `http://127.0.0.1:10501/github/pommeverte/mopimopi/?HOST_PORT=ws://127.0.0.1:10501/` (change ip if appropriate.

Then remove the old ones.

This only works for the English client but if people want it fixed in their language please give me the jap/korean names for seraph and demi-pheonix

For @HAERUHAERU the english localization are `Seraph` for SCH and `Demi-Pheonix` for SMN

**Comment by YuuUehara** [comment]
> I have a temp workaround for this. In you overlay manager add a new url that is the same as the old one but replace `haeruhaeru` with `pommeverte`. So something along the lines of `http://127.0.0.1:10501/github/pommeverte/mopimopi/?HOST_PORT=ws://127.0.0.1:10501/` (change ip if appropriate.
> 
> Then remove the old ones.
> 
> This only works for the English client but if people want it fixed in their language please give me the jap/korean names for seraph and demi-pheonix
> 
> For @HAERUHAERU the english localization are `Seraph` for SCH and `Demi-Pheonix` for SMN

In Japanese, Demi-Pheonix is デミ・フェニックス  and Seraph is セラフィム. It seems a wide problem with ACT's users to combining the summoned with its owner(like Pheonix and Bahamut for summoner and the living shadow(In fact I'm using Japanese client so I don't know what it called in English:(  In Japanese it's named 英雄の影身 ) for DK. It comes to Ninja as well).

**Comment by dmill-bz** [comment]
@zyc12334 Made the changes. Please try and let me know if it works. 

If anyone has the information on the MCH pet as well while we're at it. I think it's `Rook Autoturret` and `Automaton Queen` but correct me if I'm wrong.

**Comment by isar-andrei** [comment]
> @zyc12334 Made the changes. Please try and let me know if it works.
> 
> If anyone has the information on the MCH pet as well while we're at it. I think it's `Rook Autoturret` and `Automaton Queen` but correct me if I'm wrong.

Automaton Queen ([name of the player]) , i.e. "Automaton Queen (reikidd)"
